<!doctype html><html lang="en" class="unknown-theme" data-color-mode="light" data-dark-theme="light"><head><script>performance.mark('code/didStartRenderer');</script><script nonce="CfUvHkxiwwO9vhNke2uaMQ==" themeset="">if (document.documentElement.classList.contains('unknown-theme')) {
				if (!!window.matchMedia('(prefers-color-scheme: dark)').matches) {
					document.documentElement.classList.replace('unknown-theme', 'github-dark');
					document.documentElement.setAttribute('data-color-mode', 'dark');
					document.documentElement.setAttribute('data-dark-theme', 'dark');
				} else {
					document.documentElement.classList.replace('unknown-theme', 'github-light');
					document.documentElement.setAttribute('data-color-mode', 'light');
					document.documentElement.setAttribute('data-dark-theme', 'light');
				}
			}</script><meta charset="utf-8"/><meta http-equiv="Content-Security-Policy" content="
        upgrade-insecure-requests;
        block-all-mixed-content;
        default-src &#x27;none&#x27;;
        base-uri &#x27;self&#x27;;
        manifest-src
            &#x27;self&#x27;
            https://vscodeweb.azureedge.net/
            https://main.vscode-cdn.net/
            https://github.dev/
        https://assets.github.dev/
        ;
        style-src
            &#x27;self&#x27;
            &#x27;unsafe-inline&#x27;
            https://vscodeweb.azureedge.net/
            https://main.vscode-cdn.net/
            https://*.vscode-unpkg.net/
            https://github.dev/
        https://assets.github.dev/
        ;
        img-src
            &#x27;self&#x27;
            https:
            data:
            blob:
            vscode-remote-resource:
            https://github.dev/
        https://assets.github.dev/
        ;
        connect-src
            &#x27;self&#x27;
        https://assets.github.dev/
            https://*.rel.tunnels.api.visualstudio.com
        wss://*.tunnels.api.visualstudio.com/
                wss://vsls-prod-ins-usw2-private-relay.servicebus.windows.net
        wss://vsls-prod-rel-usw2-relay-1.servicebus.windows.net
        wss://vsls-prod-rel-usw2-relay-2.servicebus.windows.net
        wss://vsls-prod-rel-usw2-relay-3.servicebus.windows.net
        wss://vsls-prod-rel-usw2-relay-4.servicebus.windows.net
        wss://vsls-prod-ins-usw3-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-use-private-relay.servicebus.windows.net
        wss://vsls-prod-rel-use-relay-1.servicebus.windows.net
        wss://vsls-prod-rel-use-relay-2.servicebus.windows.net
        wss://vsls-prod-rel-use-relay-3.servicebus.windows.net
        wss://vsls-prod-rel-use-relay-4.servicebus.windows.net
        wss://vsls-prod-ins-use2-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-asse-private-relay.servicebus.windows.net
        wss://vsls-prod-rel-asse-relay-1.servicebus.windows.net
        wss://vsls-prod-rel-asse-relay-2.servicebus.windows.net
        wss://vsls-prod-rel-asse-relay-3.servicebus.windows.net
        wss://vsls-prod-rel-asse-relay-4.servicebus.windows.net
        wss://vsls-prod-ins-eun-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-euw-private-relay.servicebus.windows.net
        wss://vsls-prod-rel-euw-relay-1.servicebus.windows.net
        wss://vsls-prod-rel-euw-relay-2.servicebus.windows.net
        wss://vsls-prod-rel-euw-relay-3.servicebus.windows.net
        wss://vsls-prod-rel-euw-relay-4.servicebus.windows.net
        wss://vsls-prod-ins-uks-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-aue-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-auc-private-relay.servicebus.windows.net
        wss://vsls-prod-ins-inc-private-relay.servicebus.windows.net
        https://prod.liveshare.vsengsaas.visualstudio.com
        https://insiders.liveshare.vsengsaas.visualstudio.com
            http://*.dev.core.vsengsaas.visualstudio.com
                https://*.gallerycdn.vsassets.io
                https://vortex.data.microsoft.com/collect/v1
                https://vscode-sync.trafficmanager.net/
                https://vscode-sync-insiders.trafficmanager.net/
                https://vscode-sync-test.trafficmanager.net/
                https://marketplace.visualstudio.com/_apis/public/gallery/
                https://az764295.vo.msecnd.net/experiments/vscode-experiments.json
                https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json
                https://vscodeweb.azureedge.net/insider/
                https://vscodeweb.azureedge.net/stable/
                https://main.vscode-cdn.net/insider/
                https://main.vscode-cdn.net/stable/
                https://default.exp-tas.com/vscode/ab
                https://code.visualstudio.com/raw/
                https://vscode-auth.github.com
                https://*.gallery.vsassets.io/_apis/public/gallery/
                https://*.vscode-unpkg.net/
                https://github-cloud.githubusercontent.com/alambic/media/
                https://bingsettingssearch.trafficmanager.net/
                https://vscode.search.windows.net/
                https://vscode.blob.core.windows.net/gallery/index/
                https://marketplace.visualstudio.com/items/
                https://az764295.vo.msecnd.net/extensions/marketplace.json
                https://az764295.vo.msecnd.net/extensions/workspaceRecommendations.json.gz
                https://*.review-lab.github.com
                https://update.code.visualstudio.com/api/
                https://mobile.events.data.microsoft.com/
                https://az764295.vo.msecnd.net/profile-templates/
                https://vscode.download.prss.microsoft.com/
            https://api.github.com/
        ;
        font-src
            &#x27;self&#x27;
            https://main.vscode-cdn.net/insider/
            https://main.vscode-cdn.net/stable/
            https://vscodeweb.azureedge.net/insider/
            https://vscodeweb.azureedge.net/stable/
            https://*.vscode-unpkg.net/
            vscode-remote-resource:
            https://github.dev/
        https://assets.github.dev/
        ;
        frame-src
            &#x27;self&#x27;
            https://*.webview.codespaces.githubusercontent.com/webview/
        https://*.assets.github.dev/
            https://*.vscode-webview-test.com
                https://*.vscode-webview.net
                https://*.vscode-cdn.net/
                https://vscodeweb.azureedge.net/
        ;
        media-src
            https://assets.github.dev/
        ;
        worker-src
            https://github.dev/service-worker.js
        blob:
        ;
        child-src
            https://github.dev/service-worker.js
            blob:
        ;
        require-trusted-types-for
            &#x27;script&#x27;
        ;
        script-src
            &#x27;self&#x27;
            &#x27;nonce-CfUvHkxiwwO9vhNke2uaMQ==&#x27;
            &#x27;unsafe-eval&#x27;
            https://vscodeweb.azureedge.net/
            https://main.vscode-cdn.net/
            https://github.dev/
        https://assets.github.dev/
        ;
        trusted-types
            default
            dompurify
            TrustedFunctionWorkaround
            ExtensionScripts
            amdLoader
            cellRendererEditorText
            defaultWorkerFactory
            diffEditorWidget
            editorGhostText
            domLineBreaksComputer
            editorViewLayer
            diffReview
            extensionHostWorker
            insane
            notebookRenderer
            safeInnerHtml
            standaloneColorizer
            tokenizeToString
            webNestedWorkerExtensionHost
            webWorkerExtensionHost
            stickyScrollViewLayer
        ;
    "/><meta name="mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-title" content="Code"/><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"/><meta name="publicBaseUrl" content="https://assets.github.dev"/><link rel="shortcut icon" href="https://github.githubassets.com/favicon.ico" id="js-favicon"/><link rel="manifest" href="/static/manifest.json"><link rel="apple-touch-icon" href="https://assets.github.dev/static/apple-icon.png"><link rel="stylesheet" href="https://assets.github.dev/static/primer.css" id="js-primer-css"><link rel="stylesheet" href="https://assets.github.dev/static/splash-screen-styles.css" id="js-splash-screen-css"><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-bn.js.934018f1c72f29efc040.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-index.js.720e8ed0a686a03f8379.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-_stream_readable.js.9597f6e437ffc3eaca99.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-_stream_writable.js.1c81b0940bc879574af0.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-source-map-consumer.js.216c951187d5a778b7cd.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-main.js.8391bc1e0c46c9d4b944.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-secp256k1.js.ec08957dbf4618d00700.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-browser.js.8cc84f19667d165a43b6.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-short.js.099d976ab674df52e32a.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-ast.js.ae375b0de8e8f39f1f22.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~bootstrap~pfHelper-source-map-support.js.b894d23e06f770790687.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-moment.js.2219b85bb0cf5293f376.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-HttpManager.js.5254ed0a698fdcccc447.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-PostChannel.js.53595609fe09dac36fc3.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-dynamicproto-js.js.819b3e68f4ef6ba24964.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-BaseCore.js.7bffb053b234d15329f3.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-HelperFuncs.js.103dae03006e8f1731a8.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-EventHelpers.js.1e553a203cb083b0529f.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-ProcessTelemetryContext.js.47b66726377975287258.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app~pfHelper-Utils.js.3f0be0d6723595fe04c3.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-index.js.24bb43c60005e88644e8.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-utils.js.4a7dcb2d418ff9bccc29.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-events.js.0f3a945d2b9a3b238bc8.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-util.js.2f78ac86633fbaf29ebd.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-assert.js.b306aa69ff4b69f32152.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-linkedMap.js.f754cbf3d6b6526019dd.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-sshSessionConfiguration.js.1629987c942c330739f3.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-sshSession.js.533dae621ead725a40ab.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-sshClientSession.js.f81863df7a655d36abd7.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-keyExchangeService.js.db65102988e5ade000a2.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-sshProtocol.js.436550943738edfdc99d.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-axios.cjs.c2e693f64113844588ba.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-xterm.js.7973891c9ed09509f6c3.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-react-dom.production.min.js.afd3ea691e94a357cb58.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-google-protobuf.js.85e4f3c2cf6f8ee19b7d.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-VSLS.js.2695a30dc3fa57286d3e.js"></script><script defer="defer" src="https://assets.github.dev/static/commons-app-CodespaceHostService.v1_pb.js.09eaed67231072cd40b9.js"></script><script defer="defer" src="https://assets.github.dev/static/371.a061e5ce422731d05401.js"></script><script defer="defer" src="https://assets.github.dev/static/779.6dcb34ef20b545337173.js"></script><script defer="defer" src="https://assets.github.dev/static/66.f8b4ad657668a072b842.js"></script><script defer="defer" src="https://assets.github.dev/static/211.ebc346e063601aa74a59.js"></script><link href="https://assets.github.dev/static/app.26d12a